### Radar Plot

In [57]:
import pandas as pd

In [58]:
url = 'https://fbref.com/en/comps/Big5/stats/players/Big-5-European-Leagues-Stats'

df = pd.read_html(url, attrs = {'id':'stats_standard'})

In [59]:
df = df[0]

In [60]:
df.head(10)
df.dropna()

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4   Yunis Abdelhamid             ma MAR
4                     5  Salis Abdul Samed             gh GHA
...                 ...                ...                ...
2865               2756     Lovro Zvonarek             hr CRO
2866               2757    Martin Ødegaard             no NOR
2867               2758        Milan Đurić             ba BIH
2868               2759        Milan Đurić             ba BIH
2869               2760   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    DF              Reims          fr Ligue 1
4                    MF               Lens          fr Ligue 1
...                 ...                ...                 ...
2865                 MF      Bayern Munich       de Bundesliga
2866                 MF            Arsenal  eng Premier League
2867                 FW      Hellas Verona          it Serie A
2868                 FW              Monza          it Serie A
2869                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Playing Time         ...  \
                    Age               Born           MP Starts  ...
0                24-102               2000           16     12  ...
1                23-176               2000           25     10  ...
2                20-233               2003            7      1  ...
3                36-200               1987           26     26  ...
4                24-020               2000           25     17  ...
...                 ...                ...          ...    ...  ...
2865             18-343               2005            1      0  ...
2866             25-120               1998           29     29  ...
2867             33-329               1990           20     13  ...
2868             33-329               1990           11      9  ...
2869             21-077               2003           25      9  ...

     Per 90 Minutes                                                       \
                Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
0              0.08  0.08  0.00   0.08  0.00  0.07   0.07  0.00     0.07
1              0.00  0.19  0.19   0.19  0.16  0.11   0.28  0.16     0.28
2              0.89  0.89  0.00   0.89  0.11  0.07   0.19  0.11     0.19
3              0.00  0.12  0.12   0.12  0.10  0.01   0.11  0.10     0.11
4              0.00  0.00  0.00   0.00  0.05  0.03   0.08  0.05     0.08
...             ...   ...   ...    ...   ...   ...    ...   ...      ...
2865           0.00  0.00  0.00   0.00  0.00  0.00   0.00  0.00     0.00
2866           0.21  0.46  0.18   0.39  0.21  0.24   0.45  0.16     0.40
2867           0.07  0.45  0.30   0.37  0.34  0.09   0.43  0.16     0.25
2868           0.11  0.22  0.11   0.22  0.15  0.06   0.21  0.15     0.21
2869           0.00  0.00  0.00   0.00  0.02  0.02   0.04  0.02     0.04

     Unnamed: 37_level_0
                 Matches
0                Matches
1                Matches
2                Matches
3                Matches
4                Matches
...                  ...
2865             Matches
2866             Matches
2867             Matches
2868             Matches
2869             Matches

[2851 rows x 38 columns]

### Getting Rid of Per90Stats

In [61]:
df = df[df.columns.drop(list(df.filter(regex = 'Per 90')))]

In [62]:
df.head(10)

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4   Yunis Abdelhamid             ma MAR                 DF
4                  5  Salis Abdul Samed             gh GHA                 MF
5                  6    Laurent Abergel             fr FRA                 MF
6                  7     Matthis Abline             fr FRA                 FW
7                  8              Abner             br BRA                 DF
8                  9  Zakaria Aboukhlal             ma MAR              MF,FW
9                 10        Abdel Abqar             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League             24-102
1       Union Berlin       de Bundesliga             23-176
2     Eint Frankfurt       de Bundesliga             20-233
3              Reims          fr Ligue 1             36-200
4               Lens          fr Ligue 1             24-020
5            Lorient          fr Ligue 1             31-074
6             Nantes          fr Ligue 1             21-018
7              Betis          es La Liga             23-324
8           Toulouse          fr Ligue 1             24-057
9             Alavés          es La Liga             25-036

  Unnamed: 7_level_0 Playing Time         ... Performance      Expected       \
                Born           MP Starts  ...        CrdY CrdR       xG npxG
0               2000           16     12  ...           1    0      0.0  0.0
1               2000           25     10  ...           3    1      1.7  1.7
2               2003            7      1  ...           0    0      0.1  0.1
3               1987           26     26  ...           4    0      2.5  2.5
4               2000           25     17  ...           2    0      0.8  0.8
5               1993           28     28  ...           3    0      0.9  0.9
6               2003           18      8  ...           1    0      2.0  2.0
7               2000           19     14  ...           3    0      0.1  0.1
8               2000            9      5  ...           1    0      2.3  1.5
9               1999           21     21  ...           9    0      0.3  0.3

                Progression           Unnamed: 37_level_0
   xAG npxG+xAG        PrgC PrgP PrgR             Matches
0  0.8      0.9          19   41   24             Matches
1  1.2      2.9          26   31   56             Matches
2  0.1      0.2           2    5    7             Matches
3  0.3      2.8          34  121    7             Matches
4  0.5      1.3           8   77   20             Matches
5  2.0      2.9          33  160   47             Matches
6  1.6      3.6          18   15   70             Matches
7  0.6      0.7          13   30   57             Matches
8  0.2      1.7          15   13   50             Matches
9  0.0      0.4           5   42    0             Matches

[10 rows x 28 columns]

### Droping Double Column Names

In [63]:
df = df.droplevel(0, axis =1)

In [64]:
df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-102,2000,16,12,...,1,0,0.0,0.0,0.8,0.9,19,41,24,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,23-176,2000,25,10,...,3,1,1.7,1.7,1.2,2.9,26,31,56,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,20-233,2003,7,1,...,0,0,0.1,0.1,0.1,0.2,2,5,7,Matches
3,4,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,36-200,1987,26,26,...,4,0,2.5,2.5,0.3,2.8,34,121,7,Matches
4,5,Salis Abdul Samed,gh GHA,MF,Lens,fr Ligue 1,24-020,2000,25,17,...,2,0,0.8,0.8,0.5,1.3,8,77,20,Matches

### Filter DataFrame to show only Forwards

In [65]:
df = df[df['Pos'].str.contains('FW')]

In [66]:
df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,23-176,2000,25,10,...,3,1,1.7,1.7,1.2,2.9,26,31,56,Matches
6,7,Matthis Abline,fr FRA,FW,Nantes,fr Ligue 1,21-018,2003,18,8,...,1,0,2.0,2.0,1.6,3.6,18,15,70,Matches
8,9,Zakaria Aboukhlal,ma MAR,"MF,FW",Toulouse,fr Ligue 1,24-057,2000,9,5,...,1,0,2.3,1.5,0.2,1.7,15,13,50,Matches
10,11,Tammy Abraham,eng ENG,FW,Roma,it Serie A,26-196,1997,1,0,...,0,0,0.0,0.0,0.0,0.0,1,0,0,Matches
13,14,Bénie Adama Traore,ci CIV,"FW,MF",Sheffield Utd,eng Premier League,21-137,2002,8,3,...,0,0,0.3,0.3,0.5,0.8,7,9,14,Matches

### Filter to show only players with more than 400 minutes

In [67]:
df = df[df['Min'].astype(int)>400]

In [68]:
df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,23-176,2000,25,10,...,3,1,1.7,1.7,1.2,2.9,26,31,56,Matches
6,7,Matthis Abline,fr FRA,FW,Nantes,fr Ligue 1,21-018,2003,18,8,...,1,0,2.0,2.0,1.6,3.6,18,15,70,Matches
8,9,Zakaria Aboukhlal,ma MAR,"MF,FW",Toulouse,fr Ligue 1,24-057,2000,9,5,...,1,0,2.3,1.5,0.2,1.7,15,13,50,Matches
15,16,Akor Adams,ng NGA,FW,Montpellier,fr Ligue 1,24-077,2000,27,23,...,2,0,11.2,11.2,1.8,13.0,35,15,111,Matches
18,19,Sargis Adamyan,am ARM,"FW,MF",Köln,de Bundesliga,30-328,1993,16,6,...,2,0,3.4,3.4,1.6,5.0,15,15,34,Matches

In [69]:
df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born', 'MP',
       'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt',
       'CrdY', 'CrdR', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR',
       'Matches'],
      dtype='object')

In [74]:
# let's also make sure that the columns are of the correct type
df[['90s', 'xG', 'xAG']] = df[['90s', 'xG', 'xAG']].astype(float)
df[['Gls', 'Ast', 'G+A', 'PrgC', 'PrgP', 'PrgR']] = df[['Gls', 'Ast', 'G+A', 'PrgC', 'PrgP', 'PrgR']].astype(int)

ValueError: cannot convert float NaN to integer

In [73]:
df['goals_per_90'] = df['Gls'] / df['90s']
df['assists_per_90'] = df['Ast'] / df['90s']
df['goals_assists_per_90'] = df['G+A'] / df['90s']
df['progressive_carries_per_90'] = df['PrgC'] / df['90s']
df['progressive_passes_per_90'] = df['PrgP'] / df['90s']
df['progressive_receptions_per_90'] = df['PrgR'] / df['90s']
df['expected_goals_per_90'] = df['xG'] / df['90s']
df['expected_goals_against_per_90'] = df['xAG'] / df['90s']

TypeError: unsupported operand type(s) for /: 'str' and 'float'

In [ ]:
# We'll calculate the percentiles for each of these columns
# We will also name them as we want to see them in the radar plot
df['Goals'] = (df['goals_per_90'].rank(pct=True) * 100).astype(int)
df['Assists'] = (df['assists_per_90'].rank(pct=True) * 100).astype(int)
df['Goals + Assists'] = (df['goals_assists_per_90'].rank(pct=True) * 100).astype(int)
df['Expected Goals'] = (df['expected_goals_per_90'].rank(pct=True)  * 100).astype(int)
df['Expected Assists'] = (df['expected_assists_per_90'].rank(pct=True) * 100).astype(int)
df['Progressive Carries'] = (df['progressive_carries_per_90'].rank(pct=True) * 100).astype(int)
df['Progressive Passes'] = (df['progressive_passes_per_90'].rank(pct=True) * 100).astype(int)
df['Progressive Receptions'] = (df['progressive_receptions_per_90'].rank(pct=True) * 100).astype(int)

In [82]:
from mplsoccer import Radar

ModuleNotFoundError: No module named 'mplsoccer'

In [83]:
mbappe = df[df['Player'] == 'Kylian Mbappé']

mbappe.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Matches
1700,1636,Kylian Mbappé,fr FRA,FW,Paris S-G,fr Ligue 1,25-117,1998,26,22,...,3,0,19.5,13.0,4.9,17.9,100,106,251,Matches

In [86]:
columns_to_plot = [
'Goals', 'Assists', 'Goals + Assists', 'Expected Goals', 
    'Expected Assists', 'Progressive Carries', 'Progressive Passes', 'Progressive Receptions'
    
]


radar = Radar(
params = columns_to_plot,
min_range = [0 for _ in columns_to_plot],
max_range = [100 for _ in columns_to_plot]
    
)

NameError: name 'Radar' is not defined

In [87]:
fig,ax = radar.setup_axis()

rings_inner = radar.draw_circles ( ax=ax, facecolor = 'white', edgecolor = 'black', lw = 1, zorder =1 )

radar_output = radar.draw_radar(
    ax=ax,
    values=list(mbappe[columns_to_plot].values.flatten()),
    kwargs_radar = {'facecolor': '#77BA99'})
)

range_labels = radar.draw_range_labels(
    ax=ax, fontsize=15, frontproperties='monospace'
)

param_labels = radar.draw_range_labels(
    ax=ax, fontsize=15, frontproperties='monospace'
)

NameError: name 'radar' is not defined